name: icon_bottomsheet
description: A customized bottomsheet with dynamic icon(widget) on top. It gives a transparent background to the iconWidget which is displayed above the bottomsheet. The iconWidget is a dynamic widget and can be customized by the user. It can also be positioned as left, center or right. The background colors of the iconWidget as well as the child can be customized. The idea behind the icon_bottomsheet is to give user a bottomsheet with a customizable widget with a transparent border above it.
version: 0.0.3
homepage: https://github.com/amitmishra7/icon_bottomsheet
repository: https://github.com/amitmishra7/icon_bottomsheet
documentation: https://github.com/amitmishra7/icon_bottomsheet/blob/main/README.md

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
